baseURL = 'https://kobe.onl'
languageCode = 'en-us'
title = 'kobes log'
theme = 'risotto'

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "kobes log"
description = "personal blog of a third year cyber security student."
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/kobejk"

# Menu items
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10